const KEY='englishMasterV7Foundation';
const AI_URL_KEY='englishMasterAIUrl';
let S=load();
let ytPlayer=null;

const DAYS=[
{
 day:1,title:'Introducing Yourself',uzTitle:'O‘zingizni tanishtirish',goal:'30–60 soniyada ismingiz, yoshingiz, qayerdan ekaningiz, qayerda yashashingiz va nima qilishingizni aytish.',grammarTitle:'I am / I’m · a/an · I live in · I’m from',
 explanation:'Bugun ingliz tilida o‘zingiz haqingizda eng kerakli 5 ta gapni quramiz. Avval ma’noni o‘zbekcha tushunamiz, keyin inglizcha aytamiz, keyin eshitamiz va oxirida o‘zimiz gapiramiz.',
 words:[['hello','salom'],['hi','salom'],['name','ism'],['my','mening'],['live','yashamoq'],['from','...dan'],['country','davlat'],['city','shahar'],['student','talaba'],['teacher','o‘qituvchi'],['years old','yoshda'],['nice to meet you','tanishganimdan xursandman']],
 chunks:[['My name is John.','Mening ismim John.'],['I’m 32 years old.','Men 32 yoshdaman.'],['I’m from Uzbekistan.','Men O‘zbekistondanman.'],['I live in Tashkent.','Men Toshkentda yashayman.'],['I’m a student.','Men talabaman.'],['Nice to meet you.','Tanishganimdan xursandman.']],
 grammar:[['I am → I’m','I am Aziz. → I’m Aziz.'],['a/an','I’m a student. / I’m an engineer.'],['from vs in','I’m from Uzbekistan. = kelib chiqish. I live in Tashkent. = yashash joyi.']],
 errors:[['I am student.','I am a student.'],['I living in Uzbekistan.','I live in Uzbekistan.'],['I am from Tashkent.','To‘g‘ri, agar Tashkent sizning kelib chiqish joyingiz bo‘lsa. Hozir yashash joyi uchun: I live in Tashkent.']],
 dialogue:[['AI','Hi! What’s your name?'],['You','My name is Aziz.'],['AI','Nice to meet you, Aziz. How old are you?'],['You','I’m 25 years old.'],['AI','Where are you from?'],['You','I’m from Uzbekistan.'],['AI','Where do you live?'],['You','I live in Tashkent.'],['AI','What do you do?'],['You','I’m a student.']],
 video:{id:'w9kuy1p5FXY',title:'Greetings & Introductions — A1',source:'Daily English Easy Practice',checkpoints:[{t:20,q:'What is the main topic?',opts:['Food','Introductions','Travel'],a:1},{t:55,q:'Which phrase is used to meet someone?',opts:['Nice to meet you','See you tomorrow','How much is it?'],a:0}]},
 listening:{text:'Hi. My name is David. I’m 30 years old. I’m from Australia. I live in Sydney. I’m an engineer.',questions:[['What is his name?',['David','Daniel','John'],0],['How old is he?',['20','30','40'],1],['Where does he live?',['Melbourne','Sydney','London'],1],['What is his job?',['Teacher','Engineer','Student'],1]]},
 quiz:[['Choose the correct sentence.',['I am student.','I am a student.','I a student.'],1],['Choose the correct sentence.',['I live Uzbekistan.','I living in Uzbekistan.','I live in Uzbekistan.'],2],['“I’m from Uzbekistan” means…',['Men O‘zbekistonda yashayman.','Men O‘zbekistondanman.','Men o‘zbek tilini bilaman.'],1]],
 writing:'My name is ____. I’m ____ years old. I’m from ____. I live in ____. I’m a/an ____.',speaking:'Introduce yourself for 30–60 seconds. First use the template, then try again without looking.'
},
{
 day:2,title:'Greetings & First Conversations',uzTitle:'Salomlashish va birinchi suhbat',goal:'Odam bilan birinchi uchrashganda salomlashish, hol-ahvol so‘rash va xayrlashish.',grammarTitle:'I am / You are · contractions · too',
 explanation:'Bugun birinchi uchrashuvdagi tabiiy kichik suhbatni o‘rganamiz. “How are you?” savoliga bitta javob emas, bir nechta tabiiy javobni bilamiz.',
 words:[['good morning','xayrli tong'],['good afternoon','xayrli kun'],['good evening','xayrli kech'],['goodbye','xayr'],['see you','ko‘rishguncha'],['how are you?','qalaysiz?'],['I’m fine','yaxshiman'],['I’m good','yaxshiman'],['great','ajoyib'],['too','ham'],['nice to meet you','tanishganimdan xursandman'],['thanks','rahmat']],
 chunks:[['How are you?','Qalaysiz?'],['I’m good, thanks.','Yaxshiman, rahmat.'],['How about you?','Siz-chi?'],['Nice to meet you.','Tanishganimdan xursandman.'],['Nice to meet you too.','Men ham tanishganimdan xursandman.'],['See you later.','Keyin ko‘rishamiz.']],
 grammar:[['You are → You’re','You are good. → You’re good.'],['too = ham','Nice to meet you too.'],['How about you?','Suhbatni boshqa odamga qaytarish uchun.']],
 errors:[['How are you? — I am from Uzbekistan.','Savol hol-ahvol haqida; javob: I’m good, thanks.'],['Nice to meet you too. = Men ham...','too bu yerda “ham” ma’nosida.']],
 dialogue:[['A','Hi! How are you?'],['B','I’m good, thanks. How about you?'],['A','I’m great. Nice to meet you.'],['B','Nice to meet you too.'],['A','See you later!'],['B','See you!']],
 video:{id:'5Z62Fku1HXo',title:'A1 Greetings, Introductions & Basic Conversations',source:'Learn with Makayla',checkpoints:[{t:25,q:'Which topic is being practiced?',opts:['Greetings','Shopping','Weather'],a:0},{t:55,q:'What can you ask after “Hi”?',opts:['How are you?','How much?','Where is the station?'],a:0}]},
 listening:{text:'A: Good morning! How are you? B: I’m good, thanks. How about you? A: I’m great. Nice to meet you. B: Nice to meet you too.',questions:[['How does B feel?',['Good','Bad','Angry'],0],['What does B say after “Nice to meet you”?',['Goodbye','Nice to meet you too','See you tomorrow'],1]]},
 quiz:[['Choose the natural reply.',['I’m good, thanks.','I am from Tashkent.','I live in Uzbekistan.'],0],['Complete: Nice to meet you ___.',['too','from','in'],0],['“How about you?” is used to…',['repeat a word','ask the same question back','say goodbye'],1]],
 writing:'Write a 4-line first-meeting dialogue.',speaking:'Role-play a first meeting with the AI or a partner. Use greeting → name → how are you → nice to meet you → goodbye.'
},
{
 day:3,title:'Countries, Cities & Nationalities',uzTitle:'Davlatlar, shaharlar va millatlar',goal:'Qayerdan ekaningizni, qayerda yashashingizni va millatingizni aniq aytish.',grammarTitle:'I’m from… · I live in… · I’m Uzbek.',
 explanation:'“I’m from” va “I live in” bir xil emas. Birinchisi kelib chiqish, ikkinchisi hozirgi yashash joyini bildiradi. Bugun shu farqni ko‘p marta eshitib va gapirib mashq qilamiz.',
 words:[['country','davlat'],['city','shahar'],['capital','poytaxt'],['Uzbekistan','O‘zbekiston'],['Uzbek','o‘zbek'],['England','Angliya'],['English','ingliz'],['Turkey','Turkiya'],['Turkish','turk'],['America','Amerika'],['American','amerikalik'],['nationality','millat/fuqarolik']],
 chunks:[['I’m from Uzbekistan.','Men O‘zbekistondanman.'],['I live in Tashkent.','Men Toshkentda yashayman.'],['I’m Uzbek.','Men o‘zbekman.'],['Where are you from?','Qayerdansiz?'],['Where do you live?','Qayerda yashaysiz?'],['What is your nationality?','Millatingiz/fuqaroligingiz nima?']],
 grammar:[['from','I’m from Uzbekistan.'],['in','I live in Tashkent.'],['nationality adjective','Uzbekistan → Uzbek; England → English; Turkey → Turkish.']],
 errors:[['I live Uzbekistan.','I live in Uzbekistan.'],['I’m Uzbekistan.','I’m from Uzbekistan. / I’m Uzbek.']],
 dialogue:[['A','Where are you from?'],['B','I’m from Uzbekistan.'],['A','Where do you live?'],['B','I live in Tashkent.'],['A','What is your nationality?'],['B','I’m Uzbek.']],
 video:{id:'w9kuy1p5FXY',title:'A1 Introductions — Listen for places',source:'Daily English Easy Practice',checkpoints:[{t:35,q:'Which question asks about origin?',opts:['Where are you from?','Where do you live?','What do you do?'],a:0}]},
 listening:{text:'Hi, I’m Maria. I’m from Turkey, but I live in Berlin. I’m Turkish. My friend Sam is from England, but he lives in Tashkent.',questions:[['Where is Maria from?',['Turkey','Germany','England'],0],['Where does Maria live?',['Istanbul','Berlin','Tashkent'],1],['Where does Sam live?',['England','Tashkent','Turkey'],1]]},
 quiz:[['Choose: I’m ___ Uzbekistan.',['from','in','at'],0],['Choose: I live ___ Tashkent.',['from','in','to'],1],['Uzbekistan → ?',['Uzbek','Uzbekistanian','Uzbekish'],0]],
 writing:'Write 4 sentences: country, city, nationality and one question for a new friend.',speaking:'Answer: Where are you from? Where do you live? What is your nationality? Then ask the AI the same questions.'
},
{
 day:4,title:'Age & Personal Information',uzTitle:'Yosh va shaxsiy ma’lumotlar',goal:'Ism, yosh, tug‘ilgan kun, email va boshqa oddiy ma’lumotlarni so‘rash va aytish.',grammarTitle:'What’s…? · How old…? · My / your',
 explanation:'Bugun real hayotda ko‘p ishlatiladigan shaxsiy ma’lumot savollarini o‘rganamiz. Telefon yoki email kabi maxfiy ma’lumotlarni haqiqiy saytga kiritish shart emas — mashq uchun namuna ishlatamiz.',
 words:[['age','yosh'],['birthday','tug‘ilgan kun'],['phone number','telefon raqami'],['email address','email manzili'],['address','manzil'],['old','yoshda'],['young','yosh'],['number','raqam'],['month','oy'],['year','yil']],
 chunks:[['How old are you?','Yoshingiz nechada?'],['I’m 25 years old.','Men 25 yoshdaman.'],['What’s your birthday?','Tug‘ilgan kuningiz qachon?'],['What’s your phone number?','Telefon raqamingiz nima?'],['What’s your email address?','Email manzilingiz nima?'],['What’s your name?','Ismingiz nima?']],
 grammar:[['What’s = What is','What’s your name?'],['My / your','My name is… / What’s your name?'],['How old…?','How old are you?']],
 errors:[['How many years are you?','How old are you?'],['I have 25 years.','I’m 25 years old.']],
 dialogue:[['A','What’s your name?'],['B','My name is Emma.'],['A','How old are you?'],['B','I’m 28 years old.'],['A','What’s your birthday?'],['B','It’s in May.']],
 video:{id:'5Z62Fku1HXo',title:'A1 Basic Conversations — Personal Questions',source:'Learn with Makayla',checkpoints:[{t:40,q:'Which question asks about age?',opts:['What’s your name?','How old are you?','Where are you from?'],a:1}]},
 listening:{text:'My name is Anna. I’m 28 years old. My birthday is in May. I live in Samarkand. My email is anna@example.com.',questions:[['How old is Anna?',['18','28','38'],1],['When is her birthday?',['May','June','March'],0],['Where does she live?',['Tashkent','Samarkand','Bukhara'],1]]},
 quiz:[['Choose the correct question.',['How old are you?','How many old are you?','What old are you?'],0],['Choose the correct answer.',['I’m 25 years old.','I have 25 years.','I am 25 year.'],0],['My = ?',['sening','mening','uning'],1]],
 writing:'Create a safe practice profile using fictional information: name, age, city and birthday month.',speaking:'Answer 5 personal-information questions. Use fictional data if you prefer.'
},
{
 day:5,title:'Jobs & Study',uzTitle:'Kasb va o‘qish',goal:'Kasbingizni yoki nima bilan shug‘ullanishingizni aytish va boshqa odamdan so‘rash.',grammarTitle:'I’m a… · I’m an… · What do you do?',
 explanation:'Kasbni aytganda ko‘pincha a/an ishlatamiz: a teacher, a doctor, an engineer. “What do you do?” odatda “Nima ish qilasiz?” degani.',
 words:[['student','talaba'],['teacher','o‘qituvchi'],['doctor','shifokor'],['engineer','muhandis'],['driver','haydovchi'],['manager','menejer'],['designer','dizayner'],['developer','dasturchi'],['worker','ishchi'],['business owner','biznes egasi']],
 chunks:[['I’m a student.','Men talabaman.'],['I’m a teacher.','Men o‘qituvchiman.'],['I’m an engineer.','Men muhandisman.'],['What do you do?','Nima ish qilasiz?'],['What do you study?','Nimani o‘qiysiz?'],['Where do you work?','Qayerda ishlaysiz?']],
 grammar:[['a','a student, a teacher, a doctor'],['an','an engineer, an actor'],['What do you do?','Kasb/ish haqida umumiy savol.']],
 errors:[['I’m engineer.','I’m an engineer.'],['I’m a engineer.','I’m an engineer.']],
 dialogue:[['A','What do you do?'],['B','I’m a student.'],['A','What do you study?'],['B','I study computer science.'],['A','Where do you study?'],['B','I study at university.']],
 video:{id:'5Z62Fku1HXo',title:'A1 Basic Conversations — Work & Study Practice',source:'Learn with Makayla',checkpoints:[{t:70,q:'Which question asks about someone’s job?',opts:['What do you do?','How old are you?','Where are you from?'],a:0}]},
 listening:{text:'Hi, I’m Omar. I’m a doctor. My sister is a teacher. My brother is an engineer. We work in different places.',questions:[['What is Omar?',['Doctor','Teacher','Engineer'],0],['What is his sister?',['Doctor','Teacher','Student'],1],['What is his brother?',['Engineer','Driver','Manager'],0]]},
 quiz:[['Choose: I’m ___ teacher.',['a','an','—'],0],['Choose: I’m ___ engineer.',['a','an','the'],1],['“What do you do?” asks about…',['age','job/work','city'],1]],
 writing:'Write 4 sentences about your job or studies. Use a/an correctly.',speaking:'Tell the AI what you do, what you study, and where you work or study.'
},
{
 day:6,title:'Put It All Together',uzTitle:'Hammasini birlashtirish',goal:'Salomlashishdan boshlab o‘zingiz haqingizda tabiiy 60 soniyalik suhbat qilish.',grammarTitle:'Review day — no heavy new grammar',
 explanation:'Bugun yangi qoidani ko‘paytirmaymiz. Oldingi 5 kunni aralashtirib, real suhbatga aylantiramiz. Maqsad — tayyor matnni o‘qish emas, ma’noni eslab o‘zingiz gapirish.',
 words:[['introduce','tanishtirmoq'],['conversation','suhbat'],['question','savol'],['answer','javob'],['again','yana'],['correct','to‘g‘ri'],['practice','mashq qilmoq'],['remember','eslamoq'],['tell','aytib bermoq'],['about','haqida']],
 chunks:[['Can you introduce yourself?','O‘zingizni tanishtira olasizmi?'],['Tell me about yourself.','O‘zingiz haqingizda aytib bering.'],['What do you do?','Nima ish qilasiz?'],['Where do you live?','Qayerda yashaysiz?'],['Nice to meet you.','Tanishganimdan xursandman.'],['Can you say that again?','Buni yana ayta olasizmi?']],
 grammar:[['Review','I’m / I’m from / I live in / I’m a/an…'],['Conversation repair','Can you say that again? / I don’t understand.']],
 errors:[['I live Uzbekistan.','I live in Uzbekistan.'],['I am student.','I’m a student.'],['I am 25 years.','I’m 25 years old.']],
 dialogue:[['AI','Hi! Nice to meet you. Can you introduce yourself?'],['You','Hi! My name is…'],['AI','Where are you from?'],['You','I’m from…'],['AI','Where do you live?'],['You','I live in…'],['AI','What do you do?'],['You','I’m a/an…'],['AI','How old are you?'],['You','I’m … years old.']],
 video:{id:'5QfFI370oOc',title:'My Daily Routine in English — A1/A2 Comprehensible Input',source:'English with Patrick',checkpoints:[{t:32,q:'What happens first in the video?',opts:['Morning routine','Dinner','Going to bed'],a:0},{t:180,q:'What topic is discussed besides study?',opts:['Work','Hotels','Shopping'],a:0}]},
 listening:{text:'Hello! My name is Sara. I’m 24 years old. I’m from Uzbekistan and I live in Tashkent. I’m a designer. I like music and football. Nice to meet you!',questions:[['How old is Sara?',['24','34','42'],0],['Where does she live?',['Samarkand','Tashkent','London'],1],['What is her job?',['Teacher','Designer','Doctor'],1],['What does she like?',['Music and football','Cooking only','Travel only'],0]]},
 quiz:[['I’m ___ student.',['a','an','—'],0],['I ___ in Tashkent.',['live','am live','living'],0],['I’m ___ Uzbekistan.',['from','in','at'],0],['How old ___ you?',['is','are','am'],1]],
 writing:'Write a 6–7 sentence self-introduction without copying a template.',speaking:'Speak for 60 seconds. Include name, age, country, city, job/study and one thing you like.'
},
{
 day:7,title:'Weekly Mastery — Real Conversation Test',uzTitle:'Haftalik mastery testi',goal:'1–2 daqiqalik tanishtirish va oddiy first-meeting conversationni yordamchisiz bajarish.',grammarTitle:'Integrated review',
 explanation:'Bugun yangi material deyarli yo‘q. Siz 1-haftada o‘rgangan narsalarni yangi savollar va yangi listening bilan tekshirasiz. Natija keyingi haftadagi review va SRSga ta’sir qiladi.',
 words:[['ready','tayyor'],['master','puxta o‘zlashtirmoq'],['mistake','xato'],['review','qayta ko‘rib chiqmoq'],['confident','o‘ziga ishongan'],['clear','aniq'],['answer','javob'],['question','savol']],
 chunks:[['Tell me about yourself.','O‘zingiz haqingizda aytib bering.'],['What do you do?','Nima ish qilasiz?'],['Where are you from?','Qayerdansiz?'],['Where do you live?','Qayerda yashaysiz?'],['How old are you?','Yoshingiz nechada?'],['Nice to meet you.','Tanishganimdan xursandman.']],
 grammar:[['Integrated review','I’m / I’m from / I live in / a-an / How old are you? / What do you do?']],
 errors:[['Remember the 3 key patterns','I’m from + country · I live in + city · I’m a/an + job']],
 dialogue:[['AI','Hello! Please introduce yourself.'],['You','…'],['AI','Where are you from?'],['You','…'],['AI','Where do you live?'],['You','…'],['AI','What do you do?'],['You','…'],['AI','What do you like?'],['You','…']],
 video:{id:'w9kuy1p5FXY',title:'A1 Greetings & Introductions — Final Listening Challenge',source:'Daily English Easy Practice',checkpoints:[{t:20,q:'What is the video mainly about?',opts:['Introductions','Food','Directions'],a:0},{t:55,q:'Which skill should you practice after listening?',opts:['Speaking','Shopping','Writing numbers'],a:0}]},
 listening:{text:'Hi, my name is Alex. I’m 32 years old. I’m from Canada, but I live in London. I’m a teacher. I like football and music. Nice to meet you.',questions:[['What is his name?',['Alex','John','David'],0],['How old is he?',['22','32','42'],1],['Where is he from?',['Canada','England','Uzbekistan'],0],['Where does he live?',['Toronto','London','Paris'],1],['What is his job?',['Student','Teacher','Doctor'],1]]},
 quiz:[['Choose: I live ___ London.',['in','from','at'],0],['Choose: I’m ___ teacher.',['a','an','the'],0],['Choose the correct question.',['How old are you?','How old you are?','What old are you?'],0],['Choose: I’m ___ Uzbekistan.',['from','in','on'],0],['“What do you do?” means…',['What is your job?','Where do you live?','How old are you?'],0]],
 writing:'Write your final 7–8 sentence introduction from memory.',speaking:'Final challenge: 60–90 seconds, no template. Then answer 5 follow-up questions.',mastery:true
}
];

function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch(e){}return {day:1,xp:0,completed:[],skills:{vocab:0,grammar:0,listening:0,speaking:0,writing:0},srs:{},voice:'',aiUrl:localStorage.getItem(AI_URL_KEY)||'http://localhost:8787',quizScores:{},videoScores:{},speakingNotes:{},reviewQueue:[]};}
function save(){localStorage.setItem(KEY,JSON.stringify(S));}
function current(){return DAYS[Math.min(7,Math.max(1,S.day))-1];}
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='today')renderToday();if(id==='lesson')renderLesson();if(id==='review')renderReview();if(id==='tutor')renderTutor();if(id==='srs')renderSRS();if(id==='progress')renderProgress();if(id==='settings')renderSettings();window.scrollTo({top:0,behavior:'smooth'});}
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));}
function speak(text,rate=.82){if(!('speechSynthesis' in window)){alert('Bu brauzer audio speechni qo‘llamaydi.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=rate;u.lang='en-US';const voices=speechSynthesis.getVoices();let v=S.voice?voices.find(x=>x.name===S.voice):null;v=v||voices.find(x=>x.name&&/Samantha|Karen|Daniel|Alex|Ava|Zoe|Google US English/i.test(x.name)&&/^en/i.test(x.lang))||voices.find(x=>/^en(-|_)/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u);}
function addSRS(){const d=current();d.words.forEach(([en,uz])=>{const k=en.toLowerCase();if(!S.srs[k])S.srs[k]={en,uz,box:0,due:Date.now()}});save();alert('Bugungi so‘zlar SRS ga qo‘shildi.');}
function renderToday(){const d=current(),done=S.completed.includes(d.day),pct=Math.round(S.completed.length/7*100);document.getElementById('headerStatus').textContent=`🔥 ${S.xp} XP`;document.getElementById('today').innerHTML=`<div class="card hero"><span class="pill">Week 1 · Day ${d.day}</span><h1>${esc(d.title)}</h1><p>${esc(d.uzTitle)}</p><p class="goal">🎯 ${esc(d.goal)}</p><div class="progress"><div class="bar" style="width:${pct}%"></div></div><p>${S.completed.length}/7 kun tugallangan</p><div class="row"><button onclick="showTab('lesson')">Darsni boshlash</button><button class="secondary" onclick="addSRS()">+ SRS</button></div></div><div class="grid"><div class="card"><div class="sectionTitle">Bugungi yo‘l</div><ol><li>Yesterday recall / oldingi bilim</li><li>O‘zbekcha explanation</li><li>Vocabulary + audio</li><li>Grammar + examples</li><li>Video + checkpoint savollar</li><li>Listening + comprehension</li><li>Shadowing + speaking</li><li>Writing + mini test</li><li>AI Tutor conversation</li></ol></div><div class="card"><div class="sectionTitle">Hafta 1</div>${DAYS.map(x=>`<div class="item"><b>${x.day}. ${esc(x.title)}</b><br><span class="muted">${S.completed.includes(x.day)?'✅ Mastered':x.day===S.day?'▶️ Hozirgi dars':'🔒 Keyingi dars'}</span></div>`).join('')}</div></div>`;}
function renderLesson(){const d=current();document.getElementById('lesson').innerHTML=`<div class="card lessonHero"><span class="pill">Day ${d.day}</span><span class="pill">Foundation A0→A1</span><h1>${esc(d.title)}</h1><p class="muted">${esc(d.uzTitle)}</p><p class="goal">🎯 ${esc(d.goal)}</p><div class="explain"><b>🇺🇿 Bugungi tushuntirish</b><p>${esc(d.explanation)}</p></div></div>${renderRecall(d)}${renderVocabulary(d)}${renderGrammar(d)}${renderVideo(d)}${renderListening(d)}${renderSpeaking(d)}${renderWriting(d)}${renderQuiz(d)}<div class="stickyActions"><div class="row"><button class="green" onclick="completeDay(${d.day})">${S.completed.includes(d.day)?'✅ Day mastered':'🏆 Darsni tugatish'}</button><button class="secondary" onclick="addSRS()">SRS ga qo‘shish</button><button onclick="showTab('tutor')">🤖 AI Tutor</button></div></div>`;loadYouTubeAPI();}
function renderRecall(d){if(d.day===1)return `<div class="card"><div class="sectionTitle">1) Zero-pressure start</div><p>Bugun oldingi dars yo‘q. 30 soniya davomida ingliz tilida bilgan 3 ta so‘zingizni ayting.</p><button onclick="speak('Hello. Hi. Thank you.',.7)">🔊 Namuna audio</button></div>`;return `<div class="card"><div class="sectionTitle">1) Yesterday Recall — 5 daqiqa</div><p>Kitobni yopib, kechagi 5 ta so‘z va 2 ta gapni eslang. Keyin “Ko‘rsatish”ni bosing.</p><button class="secondary" onclick="this.nextElementSibling.classList.toggle('hidden')">Ko‘rsatish</button><div class="hidden explain"><p>${d.day===2?'Day 1: My name is… · I’m … years old · I’m from… · I live in… · I’m a/an…':'Oldingi kunlardan kamida 5 ta phrase ni ovoz chiqarib ayting.'}</p></div></div>`;}
function renderVocabulary(d){return `<div class="card"><div class="sectionTitle">2) Vocabulary + pronunciation</div><p class="muted">So‘z ustiga emas, <b>🔊</b> tugmasiga bosib audio eshiting. Bu Safari’dagi tasodifiy click muammosini kamaytiradi.</p><div class="wordGrid">${d.words.map(([en,uz])=>`<div class="wordCard"><div class="en">${esc(en)}</div><div class="uz">${esc(uz)}</div><button class="audio" onclick="speak(${JSON.stringify(en)},.68)">🔊 Eshitish</button></div>`).join('')}</div><div class="row" style="margin-top:12px"><button onclick="speak(${JSON.stringify(d.words.map(x=>x[0]).join('. '))},.72)">🔊 Hammasini eshitish</button><button class="secondary" onclick="addSRS()">+ SRS</button></div></div>`;}
function renderGrammar(d){return `<div class="card"><div class="sectionTitle">3) Grammar — o‘zbekcha tushuntirish</div><p><b>${esc(d.grammarTitle)}</b></p>${d.grammar.map(([a,b])=>`<div class="grammarBox"><b>${esc(a)}</b><div>${esc(b)}</div></div>`).join('')}<h3>⚠️ Eng ko‘p uchraydigan xatolar</h3>${d.errors.map(([a,b])=>`<div class="errorBox"><b>❌ ${esc(a)}</b><br><b>✅ ${esc(b)}</b></div>`).join('')}</div>`;}
function renderVideo(d){return `<div class="card"><div class="sectionTitle">4) 🎬 Video Listening</div><p><b>${esc(d.video.title)}</b><br><span class="muted">Manba: ${esc(d.video.source)}</span></p><div class="videoWrap"><div id="ytPlayer"></div></div><p class="small muted">Video YouTube embed orqali ko‘rsatiladi. YouTube embedding qo‘llab-quvvatlaydi; ishlab chiqarish versiyasida licensed/original videolarni ustun qo‘yamiz. </p>${d.video.checkpoints.map((c,i)=>`<div class="checkpoint"><div class="row"><button class="secondary mini" onclick="seekVideo(${c.t})">▶ ${c.t}s ga o‘tish</button><span class="muted">Checkpoint ${i+1}</span></div><p class="question">❓ ${esc(c.q)}</p>${c.opts.map((o,j)=>`<button class="choice" onclick="answerVideo(${i},${j})">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join('')}<div id="vfb${i}" class="feedback"></div></div>`).join('')}</div>`;}
function renderListening(d){return `<div class="card"><div class="sectionTitle">5) 🎧 Listening — avval matnsiz</div><p>1-marta: faqat eshiting. 2-marta: matnni oching. 3-marta: savollarga javob bering.</p><div class="audioBox"><button onclick="speak(${JSON.stringify(d.listening.text)},.76)">🔊 Listeningni eshitish</button><button class="secondary" onclick="this.nextElementSibling.classList.toggle('hidden')">Matnni ko‘rsatish</button><div class="hidden script" style="margin-top:10px">${esc(d.listening.text)}</div></div>${d.listening.questions.map((q,i)=>`<div class="checkpoint"><b>${i+1}. ${esc(q[0])}</b>${q[1].map((o,j)=>`<button class="choice" onclick="answerListening(${i},${j})">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join('')}<div id="lfb${i}" class="feedback"></div></div>`).join('')}</div>`;}
function renderSpeaking(d){return `<div class="card"><div class="sectionTitle">6) 🗣 Shadowing + Speaking</div><p><b>Shadowing:</b> gapni eshiting → takrorlang → matnsiz ayting.</p>${d.chunks.slice(0,4).map((x,i)=>`<div class="item"><div class="example">${esc(x[0])}</div><div class="translation">${esc(x[1])}</div><div class="row"><button onclick="speak(${JSON.stringify(x[0])},.72)">🔊 Listen</button><button class="secondary" onclick="speak(${JSON.stringify(x[0])},.58)">🐢 Slow</button></div></div>`).join('')}<div class="grammarBox"><b>🎙 Speaking challenge</b><p>${esc(d.speaking)}</p><button onclick="startSpeechHint()">🎤 Mikrofon bo‘yicha ko‘rsatma</button></div></div>`;}
function renderWriting(d){return `<div class="card"><div class="sectionTitle">7) ✍️ Writing</div><p>${esc(d.writing)}</p><textarea id="writingBox" rows="6" placeholder="Write here..."></textarea><div class="row" style="margin-top:8px"><button onclick="saveWriting()">Saqlash</button><button class="secondary" onclick="speak(document.getElementById('writingBox').value||'Please write your answer first.',.7)">🔊 Ovoz chiqarib o‘qish</button></div><div id="writingFeedback" class="feedback"></div></div>`;}
function renderQuiz(d){return `<div class="card"><div class="sectionTitle">8) 🧪 Mini Test</div><div class="quizGrid">${d.quiz.map((q,i)=>`<div class="quizItem"><b>${i+1}. ${esc(q[0])}</b>${q[1].map((o,j)=>`<button class="choice" onclick="answerQuiz(${i},${j})">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join('')}<div id="qfb${i}" class="feedback"></div></div>`).join('')}</div><div id="quizTotal" class="score" style="margin-top:12px"></div></div>`;}
function answerVideo(i,j){const d=current(),c=d.video.checkpoints[i],el=document.getElementById('vfb'+i);if(j===c.a){el.textContent='✅ To‘g‘ri';el.style.color='#166534';S.videoScores[d.day]=(S.videoScores[d.day]||0)+1}else{el.textContent='❌ Yana bir marta tinglab ko‘ring.';el.style.color='#991b1b'}}
function answerListening(i,j){const d=current(),q=d.listening.questions[i],el=document.getElementById('lfb'+i);if(j===q[2]){el.textContent='✅ To‘g‘ri';el.style.color='#166534'}else{el.textContent='❌ Xato — audio qayta eshiting.';el.style.color='#991b1b'}}
let quizState={};function answerQuiz(i,j){const d=current(),q=d.quiz[i],el=document.getElementById('qfb'+i);quizState[i]=j;if(j===q[2]){el.textContent='✅ Correct';el.style.color='#166534'}else{el.textContent='❌ Try again. Hint: read the Uzbek explanation.';el.style.color='#991b1b'}const done=Object.keys(quizState).length;document.getElementById('quizTotal').textContent=`${done}/${d.quiz.length} savol javoblandi`}
function seekVideo(t){if(ytPlayer&&ytPlayer.seekTo){ytPlayer.seekTo(t,true);ytPlayer.playVideo()}else alert('Video player hali tayyor emas.');}
function loadYouTubeAPI(){if(window.YT&&YT.Player){createYT();return}if(document.getElementById('yt-api'))return;const s=document.createElement('script');s.id='yt-api';s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s);window.onYouTubeIframeAPIReady=createYT;}
function createYT(){const d=current();const target=document.getElementById('ytPlayer');if(!target)return;ytPlayer=new YT.Player('ytPlayer',{height:'100%',width:'100%',videoId:d.video.id,playerVars:{playsinline:1,rel:0,modestbranding:1},events:{onReady:()=>{}}});}
function startSpeechHint(){alert('Safari’da mikrofonli speakingni keyingi bosqichda Web Speech/AI voice bilan ulaymiz. Hozircha telefon yoki Mac mikrofonini ishlatib, javobingizni baland ovozda ayting. AI Tutor matn orqali ishlaydi.');}
function saveWriting(){const d=current(),v=document.getElementById('writingBox').value.trim();S.speakingNotes[d.day]=v;save();document.getElementById('writingFeedback').textContent=v.length>20?'✅ Saqlandi. Keyin AI Tutor orqali grammar feedback olishingiz mumkin.':'✏️ Kamida bir necha gap yozing.';}
function completeDay(day){if(day!==S.day&&!S.completed.includes(day)){alert('Avval joriy darsni tugating.');return}if(!S.completed.includes(day)){S.completed.push(day);S.xp+=100;S.skills.vocab=Math.min(100,S.skills.vocab+12);S.skills.grammar=Math.min(100,S.skills.grammar+10);S.skills.listening=Math.min(100,S.skills.listening+10);S.skills.speaking=Math.min(100,S.skills.speaking+9);S.skills.writing=Math.min(100,S.skills.writing+9);if(day<7)S.day=day+1;save();}renderToday();alert(day===7?'🏆 Week 1 mastery testi ochiq. AI Tutor bilan final suhbatni bajaring.':'✅ Dars saqlandi. Keyingi kun ochildi.');showTab(day===7?'progress':'today');}
function renderReview(){const items=Object.values(S.srs);document.getElementById('review').innerHTML=`<div class="card"><div class="sectionTitle">🔁 Bugungi Review</div><p>Avval eslang, keyin javobni oching. Bu active recall uchun.</p>${items.length?items.slice(0,12).map((x,i)=>`<div class="item"><b>${i+1}. ${esc(x.en)}</b><br><button class="secondary" onclick="this.nextElementSibling.classList.toggle('hidden')">Javob</button><div class="hidden"><p>${esc(x.uz)}</p><button onclick="speak(${JSON.stringify(x.en)},.68)">🔊 Audio</button></div></div>`).join(''):'<p class="muted">SRS hozircha bo‘sh. Darsdan so‘z qo‘shing.</p>'}</div>`;}
function renderSRS(){const items=Object.values(S.srs);document.getElementById('srs').innerHTML=`<div class="card"><div class="sectionTitle">🧠 SRS</div><p>Hafta 1 so‘zlari. Keyingi versiyada box 1→2→4→7→14→30 kunlik adaptive schedule ishlaydi.</p><div class="wordGrid">${items.map(x=>`<div class="wordCard"><div class="en">${esc(x.en)}</div><div class="uz">${esc(x.uz)}</div><button class="audio" onclick="speak(${JSON.stringify(x.en)},.68)">🔊</button></div>`).join('')}</div></div>`;}
let tutorMessages=[];
function renderTutor(){document.getElementById('tutor').innerHTML=`<div class="card hero"><span class="pill">AI English Tutor</span><h1>🤖 Birga suhbat qilamiz</h1><p>AI sizning bugungi mavzuni, beginner darajani va xatolarni hisobga olib sodda inglizcha suhbat qiladi.</p></div><div class="card"><div id="chat" class="chat">${tutorMessages.length?tutorMessages.map(m=>`<div class="msg ${m.role}"><b>${m.role==='user'?'You':'Tutor'}:</b><br>${esc(m.text)}</div>`).join(''):'<div class="msg ai"><b>Tutor:</b><br>Hi! What’s your name?</div>'}</div><div class="row" style="margin-top:10px"><input id="tutorInput" placeholder="Englishda javob yozing..." onkeydown="if(event.key==='Enter')sendTutor()"><button onclick="sendTutor()">Yuborish</button><button class="secondary" onclick="speak(document.getElementById('tutorInput').value||'Hi! What is your name?',.72)">🔊</button></div><p id="tutorStatus" class="small muted">AI server: ${esc(S.aiUrl)}</p></div>`;scrollChat();}
async function sendTutor(){const input=document.getElementById('tutorInput');if(!input||!input.value.trim())return;const text=input.value.trim();tutorMessages.push({role:'user',text});input.value='';renderTutor();const status=document.getElementById('tutorStatus');status.textContent='Tutor javob tayyorlayapti…';const d=current();try{const r=await fetch(S.aiUrl.replace(/\/$/,'')+'/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:tutorMessages.slice(-8),lesson:{day:d.day,title:d.title,goal:d.goal,grammar:d.grammarTitle,words:d.words}})});if(!r.ok)throw new Error('server '+r.status);const j=await r.json();tutorMessages.push({role:'ai',text:j.reply||'Let’s try again.'});}catch(e){tutorMessages.push({role:'ai',text:localTutor(text,d)});}renderTutor();}
function localTutor(text,d){const t=text.toLowerCase();if(/my name|name is/.test(t))return 'Nice to meet you! How old are you?';if(/\b\d+\b/.test(t))return 'Great! Where are you from?';if(/uzbek|tashkent|samarkand|london|canada|turkey/.test(t))return 'Nice! Where do you live? Try: “I live in …”';if(/live/.test(t))return 'Good! What do you do? Try: “I’m a student.” or “I’m a teacher.”';return `Good try! For Day ${d.day}, use a short sentence. Can you answer: “Where are you from?”`}
function scrollChat(){const c=document.getElementById('chat');if(c)c.scrollTop=c.scrollHeight;}
function renderProgress(){const avg=Math.round(Object.values(S.skills).reduce((a,b)=>a+b,0)/Object.keys(S.skills).length);document.getElementById('progress').innerHTML=`<div class="card"><div class="sectionTitle">📊 Progress</div><div class="stats">${Object.entries(S.skills).map(([k,v])=>`<div class="stat"><small>${k}</small><br><b>${v}%</b></div>`).join('')}<div class="stat"><small>Overall</small><br><b>${avg}%</b></div></div></div><div class="card mastery"><h2>${S.completed.length>=7?'🏆 Week 1 complete':'🎯 Mastery gate'}</h2><p>${S.completed.length>=7?'Endi AI Tutor bilan 1–2 daqiqalik final suhbatni bajaring.':'Har bir kun tugagach skill score oshadi. Keyingi bosqichda real mastery scoringni quiz + listening + speaking natijalariga bog‘laymiz.'}</p></div>`;}
function renderSettings(){const voices='speechSynthesis' in window?speechSynthesis.getVoices():[];document.getElementById('settings').innerHTML=`<div class="card"><div class="sectionTitle">⚙️ Sozlamalar</div><label>AI server URL</label><input id="aiUrl" value="${esc(S.aiUrl)}"><p class="small muted">Local test: http://localhost:8787. GitHub Pages uchun keyin serverni internetga deploy qilamiz.</p><label>English voice</label><select id="voiceSelect"><option value="">Auto</option>${voices.filter(v=>/^en/i.test(v.lang)).map(v=>`<option ${S.voice===v.name?'selected':''}>${esc(v.name)}</option>`).join('')}</select><div class="row" style="margin-top:10px"><button onclick="saveSettings()">Saqlash</button><button class="secondary" onclick="speak('Hello! My name is English Master.',.75)">🔊 Test</button></div></div><div class="card"><div class="sectionTitle">🔔 Audio haqida</div><p>So‘zlar uchun audio tugmasi user click orqali speechSynthesisni chaqiradi. Keyingi production versiyada professional hosted MP3/TTS audio qo‘shamiz; browser voice asosiy audio sifatida qolmaydi.</p></div>`;}
function saveSettings(){S.aiUrl=document.getElementById('aiUrl').value.trim()||'http://localhost:8787';S.voice=document.getElementById('voiceSelect').value;localStorage.setItem(AI_URL_KEY,S.aiUrl);save();alert('Sozlamalar saqlandi.');}
window.addEventListener('load',()=>{if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>{if(document.getElementById('settings')&&!document.getElementById('settings').classList.contains('hidden'))renderSettings()};renderToday();});
